#
# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
#
---
- name: Make sure certs directory exists
  file: path="{{haproxy_base_dir}}/certs" owner="{{ansible_ssh_user}}" state=directory

- name: Create self-signed SSL cert
  command: "openssl req -new -nodes -x509 -subj '/C=US/ST=California/L=PaloAlto/O=IT/CN={{haproxy_fqdn}}' -days 3650 -keyout {{haproxy_base_dir}}/certs/server.key -out {{haproxy_base_dir}}/certs/server.crt"
  when: haproxy_new_cert

- name: Form self-signed cert pem file
  shell: "cat {{ haproxy_base_dir }}/certs/server.crt {{haproxy_base_dir}}/certs/server.key > {{haproxy_base_dir}}/certs/server.pem"
  when: haproxy_new_cert

- name: Set self signed pem file into vars
  include_vars: main.yml
  when: haproxy_new_cert

- name: Write haproxy config
  template:
    src:   haproxy.cfg.j2
    dest:  "{{ haproxy_base_dir }}/haproxy.cfg"

- name: Docker requires docker-py
  pip: name=docker-py


- name: haproxy container
  sudo: yes
  docker:
    name: haproxy
    image: "{{ haproxy_docker_image }}"
    state: restarted
    expose:
    - "80"
    - "443"
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - "{{haproxy_base_dir}}/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
    - "{{haproxy_base_dir}}/certs:/usr/local/etc/haproxy/certs:ro"
    links:
    - "{{haproxy_backend_container}}:{{haproxy_backend_container}}"
